= rabbitmq-formula

https://travis-ci.com/saltstack-formulas/rabbitmq-formula[image:https://travis-ci.com/saltstack-formulas/rabbitmq-formula.svg?branch=master[Travis CI Build Status]]
https://github.com/semantic-release/semantic-release[image:https://img.shields.io/badge/%20%20%F0%9F%93%A6%F0%9F%9A%80-semantic--release-e10079.svg[Semantic Release]]
https://github.com/pre-commit/pre-commit[image:https://img.shields.io/badge/pre--commit-enabled-brightgreen?logo=pre-commit&logoColor=white[pre-commit]]

This formula installs and configures RabbitMQ server on GNU/Linux.

== General notes

See the full
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html[SaltStack
Formulas installation and usage instructions].

If you are interested in writing or contributing to formulas, please pay
attention to the
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#writing-formulas[Writing
Formula Section].

If you want to use this formula, please pay attention to the `FORMULA`
file and/or `git tag`, which contains the currently released version.
This formula is versioned according to http://semver.org/[Semantic
Versioning].

See
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#versioning[Formula
Versioning Section] for more details.

If you need (non-default) configuration, please refer to:

* xref:main::map.jinja.adoc[how to configure the formula with map.jinja]
* the `pillar.example` file
* the link:#_special_notes[Special notes] section

== Contributing to this repo

=== Commit messages

*Commit message formatting is significant!!*

Please see
xref:main::CONTRIBUTING.adoc[How
to contribute] for more details.

=== pre-commit

https://pre-commit.com/[pre-commit] is configured for this formula,
which you may optionally use to ease the steps involved in submitting
your changes. First install the `pre-commit` package manager using the
appropriate https://pre-commit.com/#installation[method], then run
`bin/install-hooks` and now `pre-commit` will run automatically on each
`git commit`. :

....
$ bin/install-hooks
pre-commit installed at .git/hooks/pre-commit
pre-commit installed at .git/hooks/commit-msg
....

== Special notes

None

== Available states

=== `rabbitmq`

_Meta-state (This is a state that includes other states)_.

This installs the rabbitmq package, manages the rabbitmq configuration
file and then starts the associated rabbitmq service.

=== `rabbitmq.package`

This state will install the rabbitmq package and has a dependency on
`rabbitmq.install` via include list.

=== `rabbitmq.rabbitmqadmin`

This state will install the rabbitmqadmin package only.

=== `rabbitmq.config`

This state will configure the rabbitmq service and has a dependency on
`rabbitmq.install` via include list. See `pillar.example`.

=== `rabbitmq.service`

This state will start the rabbitmq service and has a dependency on
`rabbitmq.config` via include list.

=== `rabbitmq.clean`

_Meta-state (This is a state that includes other states)_.

this state will undo everything performed in the `rabbitmq` meta-state
in reverse order, i.e. stops the service, removes the configuration file
and then uninstalls the package.

=== `rabbitmq.service.clean`

This state will stop the rabbitmq service and disable it at boot time.

=== `rabbitmq.rabbitmqadmin.clean`

This state will remote the rabbitmqadmin package only.

=== `rabbitmq.config.clean`

This state will remove the configuration of the rabbitmq service and has
a dependency on `rabbitmq.service.clean` via include list.

=== `rabbitmq.package.clean`

This state will remove the rabbitmq package and has a depency on
`rabbitmq.config.clean` via include list.

_Meta-state (This is a state that includes other states)_.

== Testing

Linux testing is done with `kitchen-salt`.

=== Requirements

* Ruby
* Docker

[source,bash]
----
$ gem install bundler
$ bundle install
$ bin/kitchen test [platform]
----

Where `[platform]` is the platform name defined in `kitchen.yml`, e.g.
`debian-9-2019-2-py3`.

=== `bin/kitchen converge`

Creates the docker instance and runs the `rabbitmq` main state, ready
for testing.

=== `bin/kitchen verify`

Runs the `inspec` tests on the actual instance.

=== `bin/kitchen destroy`

Removes the docker instance.

=== `bin/kitchen test`

Runs all of the stages above in one go: i.e. `destroy` + `converge` +
`verify` + `destroy`.

=== `bin/kitchen login`

Gives you SSH access to the instance for manual testing.
